version: '3'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    depends_on:
      - pg
    ports:
      - "3002:3002"
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules/
      - staticfiles:/app/static
  pg:
    image: postgres
    restart: always
    env_file:
      - db.env
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  pgdata:
  staticfiles: