version: '3'

services:
  backend:
    image: ghcr.io/alekseyverba/animal:latest
    restart: always
    depends_on:
      - pg
    ports:
      - "3020:3020"
    env_file:
      - ../.env
    volumes:
      - staticfiles:/app/static
  pg:
    image: postgres
    restart: always
    ports:
      - "5430:5432"
    env_file:
      - ../db.env
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  pgdata:
  staticfiles:
